### ISSUE TITLE
Weird behaviour on Mobile

### ISSUE THREAD

**Issue by paschalidi** [hanford/react-drag-drawer#11]
When on mobile and moving up and down the Drawer then the whole page is scrolling, while only the drawer should scroll.

**Comment by hanford** [comment]
@paschalidi this should be fixed in a very recent version, published yesterday. 

Can you provide some more information, device, version, etc

**Comment by paschalidi** [comment]
@hanford I believe it is device irrelevant. 

So if you go to Chrome to the example and you open device tools, then you choose a device, then open the drawer and try to grab it with the mouse (which at the moment behaves as finger) and move it up and down you will see that the page itself moves whereas it should only the drawer to scroll.

**Comment by hanford** [comment]
@paschalidi that's an old version of the library, give me a few moments and I'll update it.

**Comment by hanford** [comment]
@paschalidi should be updated [here](https://react-drag-drawer.jackhanford.com)

**Comment by paschalidi** [comment]
@hanford thanks for the quick reply. I updated the version indeed but the problem is still there.

In the example the height of the page is not enough for the issue to appear but this is is there.

**Comment by hanford** [comment]
@paschalidi ahh, I looked a little deeper and I think the issue may be because you're not using `body` scrolling. Is something `height:100%` and that's your scroll container?

If so, can you try using this prop .. I'm realizing now it's not documented, I'll fix that soon.

**Comment by hanford** [comment]
Assuming this fixed your issue

**Comment by paschalidi** [comment]
@hanford issues is fixed after your update. 
Really appreciate your help
